version: '3.4'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - DB_NAME=data_exhaust
      - POSTGRES_USER=data_exhaust
      - POSTGRES_PASSWORD=data_exhaust
    ports:
      - 9100:5432
  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - 5373:5672
      - 15373:15672
    environment:
      - RABBITMQ_DEFAULT_USER=data_exhaust
      - RABBITMQ_DEFAULT_PASS=data_exhaust
      - RABBITMQ_DEFAULT_VHOST=data_exhaust
  celery:
    build: .
    command: celery -A data_exhaust.celeryapp worker -Q default -l debug
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbit
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8200
    image: app
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8200:8200"
    depends_on:
      - migrate
      - postgres
      - rabbit
  make-migrations:
    build: .
    command: python manage.py makemigrations
    image: app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbit
  migrate:
    build: .
    command: python manage.py migrate
    image: app
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - make-migrations
  tests:
    build:
      context: .
      dockerfile: test.Dockerfile
    command: sh -c "flake8 && coverage run --branch -m pytest -v --ds=data_exhaust.settings && coverage report"
    image: app
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - migrate
      - postgres

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    depends_on:
      - celery
