version: '3.4'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${POSTGRESQL_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - 9100:5432
  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=vhost
  celery:
    build: .
    command: celery -A data_exhaust.celeryapp worker -Q default -l debug
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRESQL_DB_USER}
      - DB_PASS=${POSTGRESQL_PASSWORD}
      - DJANGO_SECRET_KEY=${DJ_SECRET_KEY}
      - CELERY_BROKER_URL=amqp://${BROKER_USER}:${BROKER_PASSWORD}@rabbit:5672/vhost
    depends_on:
      - postgres
      - rabbit
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    image: app
    restart: always
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRESQL_DB_USER}
      - DB_PASS=${POSTGRESQL_PASSWORD}
      - DJANGO_SECRET_KEY=${DJ_SECRET_KEY}
      - CELERY_BROKER_URL=amqp://${BROKER_USER}:${BROKER_PASSWORD}@rabbit:5672/vhost
    ports:
      - "8000:8000"
    depends_on:
      - migrate
      - postgres
      - rabbit
  make-migrations:
    build: .
    command: python manage.py makemigrations
    image: app
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRESQL_DB_USER}
      - DB_PASS=${POSTGRESQL_PASSWORD}
      - DJANGO_SECRET_KEY=${DJ_SECRET_KEY}
      - CELERY_BROKER_URL=amqp://${BROKER_USER}:${BROKER_PASSWORD}@rabbit:5672/vhost
    depends_on:
      - postgres
      - rabbit
  migrate:
    build: .
    command: python manage.py migrate
    image: app
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRESQL_DB_USER}
      - DB_PASS=${POSTGRESQL_PASSWORD}
      - DJANGO_SECRET_KEY=${DJ_SECRET_KEY}
      - CELERY_BROKER_URL=amqp://${BROKER_USER}:${BROKER_PASSWORD}@rabbit:5672/vhost
    depends_on:
      - make-migrations

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://${BROKER_USER}:${BROKER_PASSWORD}@rabbit:5672/vhost
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    depends_on:
      - celery
