# Generated by Django 3.1.3 on 2020-11-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone')], db_index=True, max_length=6)),
                ('hashed_identifier', models.CharField(db_index=True, max_length=255)),
                ('signal_value', models.CharField(choices=[('bounced', 'bounced'), ('opened', 'opened'), ('clicked', 'clicked'), ('No Answer', 'No Answer'), ('Bad Contact', 'Bad Contact'), ('Do Not Contact', 'Do Not Contact'), ('Answered, Call Back', 'Answered, Call Back'), ('Send More Info', 'Send More Info'), ('Register', 'Register'), ('On Demand', 'On Demand'), ('Un-registered', 'Un-registered')], db_index=True, max_length=80)),
                ('valid', models.BooleanField(db_index=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('signal_meta', models.JSONField(help_text='Contains event and contact data e.g. seniority, job options', verbose_name='Signal Meta Data')),
            ],
        ),
    ]
