# Generated by Django 2.2.9 on 2020-11-10 20:46

from django.db import migrations, models
import djongo.models.fields
import signal_data.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSignal',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone')], max_length=6)),
                ('hashed_identifier', models.CharField(max_length=255)),
                ('signal_value', models.CharField(choices=[('bounced', 'bounced'), ('opened', 'opened'), ('clicked', 'clicked'), ('No Answer', 'No Answer'), ('Bad Contact', 'Bad Contact'), ('Do Not Contact', 'Do Not Contact'), ('Answered, Call Back', 'Answered, Call Back'), ('Send More Info', 'Send More Info'), ('Register', 'Register'), ('On Demand', 'On Demand'), ('Un-registered', 'Un-registered')], max_length=80)),
                ('valid', models.BooleanField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(help_text='Name of event where this signal originated', max_length=255)),
                ('seniority', djongo.models.fields.ArrayField(model_container=signal_data.models.Item, model_form_class=signal_data.models.ItemForm)),
                ('job_functions', djongo.models.fields.ArrayField(model_container=signal_data.models.Item, model_form_class=signal_data.models.ItemForm)),
            ],
        ),
    ]
