# Generated by Django 3.1.3 on 2020-11-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_data', '0003_auto_20201113_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasignal',
            name='signal_value',
            field=models.CharField(choices=[('bounced', 'bounced'), ('opened', 'opened'), ('clicked', 'clicked'), ('no-answer', 'no-answer'), ('bad-contact', 'bad-contact'), ('do-not-contact', 'do-not-contact'), ('answered-call-back', 'answered-call-back'), ('send-more-info', 'send-more-info'), ('register', 'register'), ('on-demand', 'on-demand'), ('un-registered', 'un-registered'), ('unsubscribe', 'unsubscribe'), ('complaint', 'complaint')], db_index=True, max_length=80),
        ),
    ]
