# Generated by Django 3.1.3 on 2020-11-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signal_data', '0005_datasignal_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasignal',
            name='signal_value',
            field=models.CharField(db_index=True, default='catch_all', max_length=120),
        ),
    ]
