# Generated by Django 3.1.3 on 2020-11-18 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signal_data', '0006_auto_20201116_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasignal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
